- hosts: localhost
  vars:
    - source_qcow2: 
        file: /root/rhel-8.6-x86_64-kvm-rootpw-Redhat01.qcow2
        rootfs: /dev/sda3
        variant: rhel8.5
    - virtual_machines:
      - servername: utility.example.com
        vcpus: 2
        ram_mb: 8192
        rootfs_gb: 20
        network:
          - host_bridge: br0
            ipv4_address: 192.168.0.6
            ipv4_prefix: 24
            ipv4_gateway: 192.168.0.1
            ipv4_defroute: true
  vars_files:
    - vault/root_pw_vault.yml
  tasks:
    - name: Create VM
      include_role:
        name: create-vm
      loop: "{{ virtual_machines }}"
    
