- hosts: provisioner
  vars:
    configure_host:
      boolean:
        libvirt: yes
        networking: yes
        firewalld: yes
        dns: yes
        ntp: yes
      setting:
        baremetal_interface: eth0
        provisioning_interface: eth1
    dns_servers:
      - 192.168.0.6
      - 192.168.254.200
      - 192.168.254.201
    ntp_servers:
      - 192.168.0.6
      - 192.168.254.250
      - 192.168.254.251
    kni_use_provisioning_network: true
    install_config:
      base_domain: example.com
      cluster_name: ocp
      external_bridge: br0
      machine_network_cidr: 192.168.0.0/25
      provisioning_bridge: br1
      provisioning_network_cidr: 172.16.0.0/24
      provisioning_dhcp_range: 172.16.0.50,172.16.0.100
      bootstrap_external_ip: 192.168.0.8
      bootstrap_external_prefix: 25
      bootstrap_external_gateway: 192.168.0.1
      bootstrap_provisioning_ip: 172.16.0.8
      bootstrap_provisioning_prefix: 24
      bootstrap_dns_configuration: 192.168.0.6;192.168.254.200;192.168.254.201;
      ntp_server_configuration: 192.168.0.6
      cluster_provisioning_nic: ens1
      api_vip: 192.168.0.11
      ingress_vip: 192.168.0.10
      baremetal:
        use_nmstate: true
        hosts:
          - { role: master, role_index: 0, bmc_type: redfish, bmc_ip: '192.168.0.151', boot_mac: 'AA:BB:CC:DD:01', external_nic: ens0, external_ip: 192.168.0.20, external_vlan: 100 }
          - { role: master, role_index: 1, bmc_type: redfish, bmc_ip: '192.168.0.152', boot_mac: 'AA:BB:CC:DD:02', external_nic: ens0, external_ip: 192.168.0.21, external_vlan: 100 }
          - { role: master, role_index: 2, bmc_type: redfish, bmc_ip: '192.168.0.153', boot_mac: 'AA:BB:CC:DD:03', external_nic: ens0, external_ip: 192.168.0.22, external_vlan: 100 }
          - { role: worker, role_index: 0, bmc_type: redfish, bmc_ip: '192.168.0.154', boot_mac: 'AA:BB:CC:DD:04', external_nic: ens0, external_ip: 192.168.0.30, external_vlan: 100 }
          - { role: worker, role_index: 1, bmc_type: redfish, bmc_ip: '192.168.0.155', boot_mac: 'AA:BB:CC:DD:05', external_nic: ens0, external_ip: 192.168.0.31, external_vlan: 100 }
  vars_files:
    - vault/baremetal_credentials.yml # Contains variables baremetal_root and baremetal_password
    - vault/kni_password.yml          # Contains variable kni_user_password
    - vault/pull_secret.yml           # Contains variable pull_secret
  roles:
    - ocp-provisioner-role
